In [13]:
from  selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import time

options = Options()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
#options.add_argument("--headless=new")
options.add_argument("--window-size=1920,1080")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--disable-notifications")
options.add_argument("--disable-popup-blocking")
driver = webdriver.Chrome (options=options)
driver.get('https://wuzzuf.net/')

positions=['Data engineer','Data Science' ,'AI Developer','Machine Learning Engineer']
counter=0
jobs_info=[]
pages=3
for i in positions:
    time.sleep(5)
    driver.find_element(By.NAME,'q').send_keys(i , Keys.ENTER)
    time.sleep(2)
    driver.refresh()
    time.sleep(4)
    for j in range(pages):
        jobs=driver.find_elements(By.CLASS_NAME,'css-pkv5jc')
        time.sleep(5)
        for job in jobs:
            
            try:
                job_number= counter
            except:
                job_number= 'there isnot'
            try:
                job_title=job.find_element(By.CLASS_NAME,'css-o171kl').text
            except:
                job_title='there isnot'
            try:
                job_href=job.find_element(By.CLASS_NAME,'css-o171kl').get_attribute('href')
            except:
                job_href='there isnot'

            try:
                job_company=job.find_element(By.CLASS_NAME,'css-ipsyv7').text
            except:
                job_company='there isnot'
            
            try:
                job_location=job.find_element(By.CLASS_NAME,'css-16x61xq').text
            except:
                job_location='there isnot'

            try:
                job_type= job.find_element(By.CLASS_NAME,'css-5jhz9n').text. replace ('\n','/')
            except:
                job_type= 'there isnot'

            try:
                job_exp=job.find_element(By.CSS_SELECTOR,'div > div.css-1rhj4yg > div:nth-child(2) > span').text
            except:
                job_exp='there isnot'
            
        
            counter+=1
            jobs_info.append(
            {
                'job number': job_number,
                'job_title':job_title,
                'job_href':job_href,
                'job_company':job_company,
                'job_location':job_location,
                'job_type':job_type,
                'job_exp':job_exp,
                'job_category': i
            }
            )
        try:
            driver.find_element(By.XPATH, "//a[@aria-label='Next page']//i[@class='css-b80bsd efou2fk0']//*[name()='svg']").click()
            time.sleep(3)
        except:
            print('problem')
            break

    time.sleep(5)

problem

In [14]:
jobs_info
import pandas as pd
df=pd.DataFrame(jobs_info)
df

,job number,job_title,job_href,job_company,job_location,job_type,job_exp,job_category
0,0,Associate System Engineer “Associate Data Mana...,https://wuzzuf.net/jobs/p/ubsrja3n94m1-associa...,Target Integrated Systems -,"Cairo, Egypt",Full Time/On-site,· 0 - 3 Yrs of Exp,Data engineer
1,1,Senior Data Engineer,https://wuzzuf.net/jobs/p/3x6prdwpt2tz-senior-...,Vertex Technologies -,"Cairo, Egypt",Full Time/On-site,· 5+ Yrs of Exp,Data engineer
2,2,Data Center Facility Electrical/ Mechanical En...,https://wuzzuf.net/jobs/p/39xm37penfcr-data-ce...,GPX Egypt -,"New Cairo, Cairo, Egypt",Full Time/On-site,· 3 - 5 Yrs of Exp,Data engineer
3,3,Data Engineer (Infrastructure & Operations),https://wuzzuf.net/jobs/p/mhqqwhx31ryd-data-en...,MEAHCO - Saudi German Health -,"Katameya, Cairo, Egypt",Full Time/On-site,· 5 - 8 Yrs of Exp,Data engineer
4,4,Sr. Data Engineer - Spark,https://wuzzuf.net/jobs/p/4w6f7tucldaf-sr-data...,Techsa -,"Cairo, Egypt",Full Time/Remote,· 7+ Yrs of Exp,Data engineer
...,...,...,...,...,...,...,...,...
161,161,GIS Technician,https://wuzzuf.net/jobs/p/hlkkamp5vekw-gis-tec...,Citylogix ME -,"Katameya, Cairo, Egypt",Full Time/On-site,· 1 - 2 Yrs of Exp,Machine Learning Engineer
162,162,Junior System Administrator,https://wuzzuf.net/jobs/p/esh3hhmwpxnt-junior-...,SHM Industries -,"Cairo, Egypt",Full Time/On-site,· 1 - 2 Yrs of Exp,Machine Learning Engineer
163,163,Junior GIS Technician,https://wuzzuf.net/jobs/p/9brwrgjkuyjv-junior-...,Citylogix ME -,"Katameya, Cairo, Egypt",Full Time/On-site,· 0 - 3 Yrs of Exp,Machine Learning Engineer
164,164,Maintenance & Technical Support Specialist,https://wuzzuf.net/internship/okjfuagtatr5-mai...,Infinity tecs -,"Cairo, Egypt",Internship/On-site,there isnot,Machine Learning Engineer
165,165,Control Specialist & SCADA Operator,https://wuzzuf.net/jobs/p/lbhbijnit5gr-control...,Alexandria Company for Vegetable Oils Extracti...,"Bourj Alarab, Alexandria, Egypt",Full Time/On-site,· 0 - 2 Yrs of Exp,Machine Learning Engineer

In [15]:
df.to_csv("wuzzuf jobs.csv",index=False)

In [9]:
import pandas as pd
df=pd.read_csv('wuzzuf jobs.csv')
df

,job number,job_title,job_href,job_company,job_location,job_type,job_exp,job_category
0,0,Associate System Engineer “Associate Data Mana...,https://wuzzuf.net/jobs/p/ubsrja3n94m1-associa...,Target Integrated Systems -,"Cairo, Egypt",Full Time/On-site,· 0 - 3 Yrs of Exp,Data engineer
1,1,Senior Data Engineer,https://wuzzuf.net/jobs/p/3x6prdwpt2tz-senior-...,Vertex Technologies -,"Cairo, Egypt",Full Time/On-site,· 5+ Yrs of Exp,Data engineer
2,2,Data Center Facility Electrical/ Mechanical En...,https://wuzzuf.net/jobs/p/39xm37penfcr-data-ce...,GPX Egypt -,"New Cairo, Cairo, Egypt",Full Time/On-site,· 3 - 5 Yrs of Exp,Data engineer
3,3,Data Engineer (Infrastructure & Operations),https://wuzzuf.net/jobs/p/mhqqwhx31ryd-data-en...,MEAHCO - Saudi German Health -,"Katameya, Cairo, Egypt",Full Time/On-site,· 5 - 8 Yrs of Exp,Data engineer
4,4,Sr. Data Engineer - Spark,https://wuzzuf.net/jobs/p/4w6f7tucldaf-sr-data...,Techsa -,"Cairo, Egypt",Full Time/Remote,· 7+ Yrs of Exp,Data engineer
...,...,...,...,...,...,...,...,...
161,161,GIS Technician,https://wuzzuf.net/jobs/p/hlkkamp5vekw-gis-tec...,Citylogix ME -,"Katameya, Cairo, Egypt",Full Time/On-site,· 1 - 2 Yrs of Exp,Machine Learning Engineer
162,162,Junior System Administrator,https://wuzzuf.net/jobs/p/esh3hhmwpxnt-junior-...,SHM Industries -,"Cairo, Egypt",Full Time/On-site,· 1 - 2 Yrs of Exp,Machine Learning Engineer
163,163,Junior GIS Technician,https://wuzzuf.net/jobs/p/9brwrgjkuyjv-junior-...,Citylogix ME -,"Katameya, Cairo, Egypt",Full Time/On-site,· 0 - 3 Yrs of Exp,Machine Learning Engineer
164,164,Maintenance & Technical Support Specialist,https://wuzzuf.net/internship/okjfuagtatr5-mai...,Infinity tecs -,"Cairo, Egypt",Internship/On-site,there isnot,Machine Learning Engineer
165,165,Control Specialist & SCADA Operator,https://wuzzuf.net/jobs/p/lbhbijnit5gr-control...,Alexandria Company for Vegetable Oils Extracti...,"Bourj Alarab, Alexandria, Egypt",Full Time/On-site,· 0 - 2 Yrs of Exp,Machine Learning Engineer

In [10]:
output= list(df.itertuples(index=None, name=None))
output

[(0,
  'Associate System Engineer “Associate Data Management Engineer',
  'https://wuzzuf.net/jobs/p/ubsrja3n94m1-associate-system-engineer-associate-data-management-engineer-target-integrated-systems-cairo-egypt',
  'Target Integrated Systems -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 0 - 3 Yrs of Exp',
  'Data engineer'),
 (1,
  'Senior Data Engineer',
  'https://wuzzuf.net/jobs/p/3x6prdwpt2tz-senior-data-engineer-vertex-technologies-cairo-egypt',
  'Vertex Technologies -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 5+ Yrs of Exp',
  'Data engineer'),
 (2,
  'Data Center Facility Electrical/ Mechanical Engineer',
  'https://wuzzuf.net/jobs/p/39xm37penfcr-data-center-facility-electrical-mechanical-engineer-gpx-egypt-cairo-egypt',
  'GPX Egypt -',
  'New Cairo, Cairo, Egypt',
  'Full Time/On-site',
  '· 3 - 5 Yrs of Exp',
  'Data engineer'),
 (3,
  'Data Engineer (Infrastructure & Operations)',
  'https://wuzzuf.net/jobs/p/mhqqwhx31ryd-data-engineer-infrastructure-operations-meahco-saudi-german-health-cairo-egypt',
  'MEAHCO - Saudi German Health -',
  'Katameya, Cairo, Egypt',
  'Full Time/On-site',
  '· 5 - 8 Yrs of Exp',
  'Data engineer'),
 (4,
  'Sr. Data Engineer - Spark',
  'https://wuzzuf.net/jobs/p/4w6f7tucldaf-sr-data-engineer-spark-techsa-cairo-egypt',
  'Techsa -',
  'Cairo, Egypt',
  'Full Time/Remote',
  '· 7+ Yrs of Exp',
  'Data engineer'),
 (5,
  'Sr. Data Engineer - Flink',
  'https://wuzzuf.net/jobs/p/kxuhb21u1pz5-sr-data-engineer-flink-techsa-cairo-egypt',
  'Techsa -',
  'Cairo, Egypt',
  'Full Time/Remote',
  '· 7+ Yrs of Exp',
  'Data engineer'),
 (6,
  'Principal Data Engineer',
  'https://wuzzuf.net/jobs/p/2hly9qsdamhe-principal-data-engineer-vertex-technologies-cairo-egypt',
  'Vertex Technologies -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 6+ Yrs of Exp',
  'Data engineer'),
 (7,
  'Production Planning Engineer',
  'https://wuzzuf.net/jobs/p/nebtxse2to5r-production-planning-engineer-badawy-beeco-cairo-egypt',
  'Badawy - BEECO -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 3+ Yrs of Exp',
  'Data engineer'),
 (8,
  'Technical Support & Quality Engineer',
  'https://wuzzuf.net/jobs/p/24a55ggjdiio-technical-support-quality-engineer-bouri-group-cairo-egypt',
  'Bouri Group -',
  'New Cairo, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 4 - 7 Yrs of Exp',
  'Data engineer'),
 (9,
  'Planning Engineer',
  'https://wuzzuf.net/jobs/p/nqbt5abgv20b-planning-engineer-saudi-firmness-cairo-egypt',
  'Saudi-firmness -',
  'Katameya, Cairo, Egypt',
  'Full Time/On-site',
  '· 1 - 2 Yrs of Exp',
  'Data engineer'),
 (10,
  'Industrial Engineer',
  'https://wuzzuf.net/jobs/p/pgfjoz30wrgh-industrial-engineer-sharqia-egypt',
  'Confidential -',
  '10th of Ramadan City, Sharqia, Egypt',
  'Full Time/On-site',
  '· 7 - 10 Yrs of Exp',
  'Data engineer'),
 (11,
  'Senior Machine Learning Engineer',
  'https://wuzzuf.net/jobs/p/etxcwinbdjs4-senior-machine-learning-engineer-techjump-alexandria-egypt',
  'TechJump -',
  'Alexandria, Egypt',
  'Full Time/Hybrid',
  '· 3 - 7 Yrs of Exp',
  'Data engineer'),
 (12,
  'Facility Management Performance & Quality Engineer',
  'https://wuzzuf.net/jobs/p/6bjjkccradum-facility-management-performance-quality-engineer-lasirena-group-cairo-egypt',
  'Lasirena Group -',
  'Maadi, Cairo, Egypt',
  'Full Time/On-site',
  '· 7 - 10 Yrs of Exp',
  'Data engineer'),
 (13,
  'SAP Master Data Administrator',
  'https://wuzzuf.net/jobs/p/tre5cqqrxiqf-sap-master-data-administrator-amreyah-cement-cairo-egypt',
  'Amreyah Cement -',
  'Nasr City, Cairo, Egypt',
  'Full Time/On-site',
  '· 3 - 7 Yrs of Exp',
  'Data engineer'),
 (14,
  'Project Quality Engineer',
  'https://wuzzuf.net/jobs/p/ihtdsvgl3sxh-project-quality-engineer-icpm-cairo-egypt',
  'ICPM -',
  'Sahel, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 2 - 5 Yrs of Exp',
  'Data engineer'),
 (15,
  'Quality Control Engineer',
  'https://wuzzuf.net/jobs/p/usgnlqznm4dr-quality-control-engineer-soudanco-port-said-egypt',
  'Soudanco -',
  'Port Said, Egypt',
  'Full Time/On-site',
  '· 1 - 3 Yrs of Exp',
  'Data engineer'),
 (16,
  'Sales Engineer',
  'https://wuzzuf.net/jobs/p/iqwa14gfeell-sales-engineer-onspec-tawakol-engineering-contracting-cairo-egypt',
  'Onspec Engineering and Contracting -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 3 - 7 Yrs of Exp',
  'Data engineer'),
 (17,
  'Quality Manager (Chemical Engineering)',
  'https://wuzzuf.net/jobs/p/jqaqwtgdkjyp-quality-manager-chemical-engineering-rockal-sharqia-egypt',
  'Rockal -',
  'Belbes, Sharqia, Egypt',
  'Full Time/On-site',
  '· 5 - 10 Yrs of Exp',
  'Data engineer'),
 (18,
  'MLOps Engineer',
  'https://wuzzuf.net/jobs/p/ol7kpd5vvteu-mlops-engineer-etisalat-egypt-cairo-egypt',
  'Etisalat Egypt -',
  'Cairo, Egypt',
  'Full Time/Hybrid',
  '· 2 - 4 Yrs of Exp',
  'Data engineer'),
 (19,
  'Production Engineer',
  'https://wuzzuf.net/jobs/p/usmxetvianxm-production-engineer-sharqia-egypt',
  'Confidential -',
  '10th of Ramadan City, Sharqia, Egypt',
  'Full Time/On-site',
  '· 3 - 7 Yrs of Exp',
  'Data engineer'),
 (20,
  'Data Engineer (Apache Spark)',
  'https://wuzzuf.net/jobs/p/ciuesnp11aqc-data-engineer-apache-spark-aptivamena-tech-cairo-egypt',
  'Aptivamena Tech -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 7 - 15 Yrs of Exp',
  'Data engineer'),
 (21,
  'Data Engineer (Apache Flink)',
  'https://wuzzuf.net/jobs/p/xgatgsrcxajg-data-engineer-apache-flink-aptivamena-tech-cairo-egypt',
  'Aptivamena Tech -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 7 - 15 Yrs of Exp',
  'Data engineer'),
 (22,
  '(CODE-07) Presales Engineer – IT & Network',
  'https://wuzzuf.net/jobs/p/eshln6in6dxe-code-07-presales-engineer-it-network-iec-pro-cairo-egypt',
  'IEC-Pro -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 2+ Yrs of Exp',
  'Data engineer'),
 (23,
  'Data Scientist – Machine Learning & Generative AI',
  'https://wuzzuf.net/jobs/p/ygbb8ah3zfkh-data-scientist-machine-learning-generative-ai-epsilonai-cairo-egypt',
  'EpsilonAI -',
  'Nasr City, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 1 - 4 Yrs of Exp',
  'Data engineer'),
 (24,
  'AI Engineer (LLM & AI Applications)',
  'https://wuzzuf.net/jobs/p/f3fqbcncr7i6-ai-engineer-llm-ai-applications-exab-cairo-egypt',
  'Exab -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 3 - 7 Yrs of Exp',
  'Data engineer'),
 (25,
  'AI Engineer',
  'https://wuzzuf.net/jobs/p/kca9wrw4ul4l-ai-engineer-cairo-egypt',
  'Confidential -',
  'Sheraton, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 3 - 4 Yrs of Exp',
  'Data engineer'),
 (26,
  'Senior Data Scientist',
  'https://wuzzuf.net/jobs/p/yzal3d0v861d-senior-data-scientist-vertex-technologies-cairo-egypt',
  'Vertex Technologies -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 5+ Yrs of Exp',
  'Data engineer'),
 (27,
  'Cost Control Engineer',
  'https://wuzzuf.net/jobs/p/lqteo3iv3stg-cost-control-engineer-saudi-firmness-cairo-egypt',
  'Saudi-firmness -',
  'Katameya, Cairo, Egypt',
  'Full Time/On-site',
  '· 4 - 5 Yrs of Exp',
  'Data engineer'),
 (28,
  'Planning Engineer',
  'https://wuzzuf.net/jobs/p/mzvc0tsma55d-planning-engineer-doosan-enerbility-co-ltd-matruh-egypt',
  'Doosan Enerbility co .LTD -',
  'Dabaa, Matruh, Egypt',
  'Full Time/On-site',
  '· 2 - 5 Yrs of Exp',
  'Data engineer'),
 (29,
  'Planning Engineer',
  'https://wuzzuf.net/jobs/p/m9xesrhuzufc-planning-engineer-etisal-for-advanced-industries-giza-egypt',
  'etisal for advanced industries -',
  '6th of October, Giza, Egypt',
  'Full Time/On-site',
  '· 0 - 2 Yrs of Exp',
  'Data engineer'),
 (30,
  'Project Control Engineer',
  'https://wuzzuf.net/jobs/p/ezasiyv4c17y-project-control-engineer-intrade-giza-egypt',
  'Intrade -',
  '6th of October, Giza, Egypt',
  'Full Time/On-site',
  '· 3 - 7 Yrs of Exp',
  'Data engineer'),
 (31,
  'Senior AI Engineer',
  'https://wuzzuf.net/jobs/p/e24mgm9chl4v-senior-ai-engineer-efada-technology-cairo-egypt',
  'Efada Technology -',
  'New Cairo, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 4+ Yrs of Exp',
  'Data engineer'),
 (32,
  'Associate Product Manager (Engineering Background)',
  'https://wuzzuf.net/jobs/p/q6qo9fkpy5ac-associate-product-manager-engineering-background-menthum-cairo-egypt',
  'Menthum -',
  'Maadi, Cairo, Egypt',
  'Full Time/On-site',
  '· 2 - 5 Yrs of Exp',
  'Data engineer'),
 (33,
  'Production Planning Engineer',
  'https://wuzzuf.net/jobs/p/eus7vl5nyxug-production-planning-engineer-cairo-egypt',
  'Confidential -',
  'Obour City, Cairo, Egypt',
  'Full Time/On-site',
  '· 3 - 5 Yrs of Exp',
  'Data engineer'),
 (34,
  'Senior Frontend Engineer (React/TypeScript)',
  'https://wuzzuf.net/jobs/p/uzrifevuk13z-senior-frontend-engineer-reacttypescript-aptivamena-tech-cairo-egypt',
  'Aptivamena Tech -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 6 - 15 Yrs of Exp',
  'Data engineer'),
 (35,
  'Software Development Manager',
  'https://wuzzuf.net/jobs/p/llqu0busdk8y-software-development-manager-uniprep-bengaluru-india',
  'UNIPREP -',
  'Bengaluru, India',
  'Full Time/Remote',
  '· 0 - 6 Yrs of Exp',
  'Data engineer'),
 (36,
  'Supply Chain Analyst',
  'https://wuzzuf.net/jobs/p/o28dqfvkorh4-supply-chain-analyst-akhnaton-trading-and-distribution-eva-group-limted-cairo-egypt',
  'Akhnaton Trading and distribution - EVA Group Limted -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 1 - 3 Yrs of Exp',
  'Data engineer'),
 (37,
  'Material Control',
  'https://wuzzuf.net/jobs/p/ggtduwl8tz85-material-control-doosan-enerbility-co-ltd-matruh-egypt',
  'Doosan Enerbility co .LTD -',
  'Dabaa, Matruh, Egypt',
  'Full Time/On-site',
  '· 5 - 10 Yrs of Exp',
  'Data engineer'),
 (38,
  'Senior Outsystems Developer',
  'https://wuzzuf.net/jobs/p/so0iisbrp8l0-senior-outsystems-developer-link-development-cairo-egypt',
  'Link Development -',
  'Cairo, Egypt',
  'Full Time/Hybrid',
  '· 3 - 6 Yrs of Exp',
  'Data engineer'),
 (39,
  'IT Manager',
  'https://wuzzuf.net/jobs/p/tap2sw5mahey-it-manager-everlast-cairo-egypt',
  'Everlast -',
  'Heliopolis, Cairo, Egypt',
  'Full Time/On-site',
  '· 5 - 10 Yrs of Exp',
  'Data engineer'),
 (40,
  'MAP Engineer',
  'https://wuzzuf.net/jobs/p/lfjwfm8aejq5-map-engineer-zatus-gmbh-benghazi-libya',
  'Zatus GmbH -',
  'Benghazi, Libya',
  'Full Time/On-site',
  '· 4 - 20 Yrs of Exp',
  'Data engineer'),
 (41,
  'Technical and Sales Operation',
  'https://wuzzuf.net/jobs/p/scibedkjkmfi-technical-and-sales-operation-turbo-compression-cairo-egypt',
  'Turbo Compression -',
  'Heliopolis, Cairo, Egypt',
  'Full Time/On-site',
  '· 5 - 9 Yrs of Exp',
  'Data engineer'),
 (42,
  'Planning Manager - Engineering',
  'https://wuzzuf.net/jobs/p/6fprvdlqbrko-planning-manager-engineering-kandil-glass-cairo-egypt',
  'Kandil Glass -',
  '10th of Ramadan City, Cairo, Egypt',
  'Full Time/On-site',
  '· 7+ Yrs of Exp',
  'Data engineer'),
 (43,
  'Quality Control Manager',
  'https://wuzzuf.net/jobs/p/2qlr37rdmo6y-quality-control-manager-classique-group-alexandria-egypt',
  'Classique Group -',
  'Sidi Bishr, Alexandria, Egypt',
  'Full Time/On-site',
  '· 6 - 10 Yrs of Exp',
  'Data engineer'),
 (44,
  'Planning & Data Supervisor',
  'https://wuzzuf.net/jobs/p/axweyysudwpr-planning-data-supervisor-family-corporation-giza-egypt',
  'Family Corporation -',
  'Haram, Giza, Egypt',
  'Full Time/On-site',
  '· 1 - 3 Yrs of Exp',
  'Data engineer'),
 (45,
  'Senior Data Engineer',
  'https://wuzzuf.net/jobs/p/3x6prdwpt2tz-senior-data-engineer-vertex-technologies-cairo-egypt',
  'Vertex Technologies -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 5+ Yrs of Exp',
  'Data Science'),
 (46,
  'SAP Master Data Administrator',
  'https://wuzzuf.net/jobs/p/tre5cqqrxiqf-sap-master-data-administrator-amreyah-cement-cairo-egypt',
  'Amreyah Cement -',
  'Nasr City, Cairo, Egypt',
  'Full Time/On-site',
  '· 3 - 7 Yrs of Exp',
  'Data Science'),
 (47,
  'Data Analyst',
  'https://wuzzuf.net/jobs/p/vclkpyuwu8wh-data-analyst-egec-giza-egypt',
  'EGEC -',
  'Haram, Giza, Egypt',
  'Full Time/On-site',
  '· 0 - 2 Yrs of Exp',
  'Data Science'),
 (48,
  'Sr. Data Engineer - Spark',
  'https://wuzzuf.net/jobs/p/4w6f7tucldaf-sr-data-engineer-spark-techsa-cairo-egypt',
  'Techsa -',
  'Cairo, Egypt',
  'Full Time/Remote',
  '· 7+ Yrs of Exp',
  'Data Science'),
 (49,
  'Sr. Data Engineer - Flink',
  'https://wuzzuf.net/jobs/p/kxuhb21u1pz5-sr-data-engineer-flink-techsa-cairo-egypt',
  'Techsa -',
  'Cairo, Egypt',
  'Full Time/Remote',
  '· 7+ Yrs of Exp',
  'Data Science'),
 (50,
  'Data Scientist – Machine Learning & Generative AI',
  'https://wuzzuf.net/jobs/p/ygbb8ah3zfkh-data-scientist-machine-learning-generative-ai-epsilonai-cairo-egypt',
  'EpsilonAI -',
  'Nasr City, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 1 - 4 Yrs of Exp',
  'Data Science'),
 (51,
  'Senior Data Scientist',
  'https://wuzzuf.net/jobs/p/yzal3d0v861d-senior-data-scientist-vertex-technologies-cairo-egypt',
  'Vertex Technologies -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 5+ Yrs of Exp',
  'Data Science'),
 (52,
  'Principal Data Engineer',
  'https://wuzzuf.net/jobs/p/2hly9qsdamhe-principal-data-engineer-vertex-technologies-cairo-egypt',
  'Vertex Technologies -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 6+ Yrs of Exp',
  'Data Science'),
 (53,
  'IT Specialist',
  'https://wuzzuf.net/jobs/p/4jfdyicnq8om-it-specialist-zad-mep-cairo-egypt',
  'ZAD MEP -',
  'Heliopolis, Cairo, Egypt',
  'Full Time/On-site',
  '· 3 - 5 Yrs of Exp',
  'Data Science'),
 (54,
  'Senior Outsystems Developer',
  'https://wuzzuf.net/jobs/p/so0iisbrp8l0-senior-outsystems-developer-link-development-cairo-egypt',
  'Link Development -',
  'Cairo, Egypt',
  'Full Time/Hybrid',
  '· 3 - 6 Yrs of Exp',
  'Data Science'),
 (55,
  'Technical Support & Quality Engineer',
  'https://wuzzuf.net/jobs/p/24a55ggjdiio-technical-support-quality-engineer-bouri-group-cairo-egypt',
  'Bouri Group -',
  'New Cairo, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 4 - 7 Yrs of Exp',
  'Data Science'),
 (56,
  'IT Manager',
  'https://wuzzuf.net/jobs/p/tap2sw5mahey-it-manager-everlast-cairo-egypt',
  'Everlast -',
  'Heliopolis, Cairo, Egypt',
  'Full Time/On-site',
  '· 5 - 10 Yrs of Exp',
  'Data Science'),
 (57,
  'Database Administrator (DBA)',
  'https://wuzzuf.net/jobs/p/9kgxhoepfg2o-database-administrator-dba-etisalat-egypt-cairo-egypt',
  'Etisalat Egypt -',
  'Cairo, Egypt',
  'Full Time/Hybrid',
  '· 2 - 3 Yrs of Exp',
  'Data Science'),
 (58,
  'Power BI Developer / BI Specialist',
  'https://wuzzuf.net/jobs/p/5hygjfkymgpa-power-bi-developer-bi-specialist-advanced-solutions-cairo-egypt',
  'Advanced Solutions -',
  'Nasr City, Cairo, Egypt',
  'Full Time/On-site',
  '· 2 - 7 Yrs of Exp',
  'Data Science'),
 (59,
  'Senior Machine Learning Engineer',
  'https://wuzzuf.net/jobs/p/etxcwinbdjs4-senior-machine-learning-engineer-techjump-alexandria-egypt',
  'TechJump -',
  'Alexandria, Egypt',
  'Full Time/Hybrid',
  '· 3 - 7 Yrs of Exp',
  'Data Science'),
 (60,
  'Governance Senior Specialist',
  'https://wuzzuf.net/jobs/p/p9tf1rptlxkl-governance-senior-specialist-etisalat-egypt-cairo-egypt',
  'Etisalat Egypt -',
  'Maadi, Cairo, Egypt',
  'Full Time/On-site',
  '· 2 - 3 Yrs of Exp',
  'Data Science'),
 (61,
  'Quality Manager (Chemical Engineering)',
  'https://wuzzuf.net/jobs/p/jqaqwtgdkjyp-quality-manager-chemical-engineering-rockal-sharqia-egypt',
  'Rockal -',
  'Belbes, Sharqia, Egypt',
  'Full Time/On-site',
  '· 5 - 10 Yrs of Exp',
  'Data Science'),
 (62,
  'Power BI Developer - Project Based',
  'https://wuzzuf.net/jobs/p/yd0g3k6ypuqo-power-bi-developer-project-based-pure-group-cairo-egypt',
  'Pure Group -',
  'Cairo, Egypt',
  'Freelance / Project/Hybrid',
  '· 3 - 7 Yrs of Exp',
  'Data Science'),
 (63,
  'AI Engineer (LLM & AI Applications)',
  'https://wuzzuf.net/jobs/p/f3fqbcncr7i6-ai-engineer-llm-ai-applications-exab-cairo-egypt',
  'Exab -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 3 - 7 Yrs of Exp',
  'Data Science'),
 (64,
  'AI Engineer',
  'https://wuzzuf.net/jobs/p/kca9wrw4ul4l-ai-engineer-cairo-egypt',
  'Confidential -',
  'Sheraton, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 3 - 4 Yrs of Exp',
  'Data Science'),
 (65,
  'Sr. Testing / QA Lead',
  'https://wuzzuf.net/jobs/p/7kjydbcqevjb-sr-testing-qa-lead-techsa-cairo-egypt',
  'Techsa -',
  'Cairo, Egypt',
  'Full Time/Remote',
  '· 6+ Yrs of Exp',
  'Data Science'),
 (66,
  'Sr. Application Solution Architect',
  'https://wuzzuf.net/jobs/p/wtflhuqz6zjr-sr-application-solution-architect-techsa-cairo-egypt',
  'Techsa -',
  'Cairo, Egypt',
  'Full Time/Remote',
  '· 12+ Yrs of Exp',
  'Data Science'),
 (67,
  'HR Data Analyst',
  'https://wuzzuf.net/jobs/p/pyqhdkta1ch6-hr-data-analyst-amreyah-cement-cairo-egypt',
  'Amreyah Cement -',
  'Sheraton, Cairo, Egypt',
  'Full Time/On-site',
  '· 1 - 3 Yrs of Exp',
  'Data Science'),
 (68,
  'IT Infrastructure Solution Architect',
  'https://wuzzuf.net/jobs/p/okaq34psvuvb-it-infrastructure-solution-architect-etisalat-egypt-cairo-egypt',
  'Etisalat Egypt -',
  'New Cairo, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 3 - 4 Yrs of Exp',
  'Data Science'),
 (69,
  'Planning & Data Supervisor',
  'https://wuzzuf.net/jobs/p/axweyysudwpr-planning-data-supervisor-family-corporation-giza-egypt',
  'Family Corporation -',
  'Haram, Giza, Egypt',
  'Full Time/On-site',
  '· 1 - 3 Yrs of Exp',
  'Data Science'),
 (70,
  'Senior AI Engineer',
  'https://wuzzuf.net/jobs/p/e24mgm9chl4v-senior-ai-engineer-efada-technology-cairo-egypt',
  'Efada Technology -',
  'New Cairo, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 4+ Yrs of Exp',
  'Data Science'),
 (71,
  'Data Analyst',
  'https://wuzzuf.net/jobs/p/zqrw3masyxwc-data-analyst-techjump-alexandria-egypt',
  'TechJump -',
  'Alexandria, Egypt',
  'Full Time/Hybrid',
  '· 3 - 7 Yrs of Exp',
  'Data Science'),
 (72,
  'Director, AI & Data CoE',
  'https://wuzzuf.net/jobs/p/3yd6fw6zovno-director-ai-data-coe-pulse-cairo-egypt',
  'PULSE -',
  'Cairo, Egypt',
  'Full Time/On-site',
  '· 10+ Yrs of Exp',
  'Data Science'),
 (73,
  'Senior BI Analyst',
  'https://wuzzuf.net/jobs/p/q9htrgprlbhs-senior-bi-analyst-ibn-sina-pharma-cairo-egypt',
  'Ibn Sina Pharma -',
  'New Cairo, Cairo, Egypt',
  'Full Time/On-site',
  '· 2 - 4 Yrs of Exp',
  'Data Science'),
 (74,
  'Senior Full stack Developer (.Net Core & Angular)',
  'https://wuzzuf.net/jobs/p/cvpdwcj5ufme-senior-full-stack-developer-net-core-angular-bi-technologies-cairo-egypt',
  'BI-Technologies -',
  'New Cairo, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 3 - 6 Yrs of Exp',
  'Data Science'),
 (75,
  'Quality Assurance Coordinator',
  'https://wuzzuf.net/jobs/p/odjrkv7zfrph-quality-assurance-coordinator-ibn-sina-pharma-cairo-egypt',
  'Ibn Sina Pharma -',
  'New Cairo, Cairo, Egypt',
  'Full Time/On-site',
  '· 1 - 2 Yrs of Exp',
  'Data Science'),
 (76,
  'IT Operations Specialist',
  'https://wuzzuf.net/jobs/p/jl53ag3l8hsn-it-operations-specialist-riseup-endemag-for-administrative-skills-development-cairo-egypt',
  'RISEUP (Endemag for Administrative Skills Development) -',
  'Maadi, Cairo, Egypt',
  'Full Time/Hybrid',
  '· 2 - 3 Yrs of Exp',
  'Data Science'),
 (77,
  'Business Analyst Lead',
  'https://wuzzuf.net/jobs/p/xyblxqvbjreb-business-analyst-lead-tawfeer-cairo-egypt',
  'Tawfeer -',
  'Maadi, Cairo, Egypt',
  'Full Time/On-site',
  '· 5 - 7 Yrs of Exp',
  'Data Science'),
 (78,
  'Business Analyst',
  'https://wuzzuf.net/jobs/p/xnpqgweb1agp-business-analyst-giza-egypt',
  'Confidential -',
  'Dokki, Giza, Egypt',
  'Full Time/On-site',
  '· 2 - 5 Yrs of Exp',
  'Data Science'),
 (79,
  'Product Owner',
  'https://wuzzuf.net/jobs/p/ntew5pwqu77n-product-owner-giza-egypt',
  'Confidential -',
  'Dokki, Giza, Egypt',
  'Full Time/On-site',
  '· 3 - 7 Yrs of Exp',
  'Data Science'),
 (80,
  'Odoo Functional Consultant',
  'https://wuzzuf.net/jobs/p/2qkymkmacqqj-odoo-functional-consultant-international-coffee-industries-cafe-najjar-egypt-giza-egypt',

In [2]:
import os 
from dotenv import load_dotenv

load_dotenv()

Server = os.getenv("Server")
Database = os.getenv("Database")

In [17]:
SQL_Query1='''create table wuzzuf_secured(
job_number  varchar(100),
job_title   varchar(100),
job_href    varchar(200),
job_company varchar(100),
job_location    varchar(50),
job_type    varchar(50),
job_exp varchar(50),
job_category varchar(50)
)
'''
SQL_Query2='insert into wuzzuf_secured values(?,?,?,?,?,?,?,?)'

In [19]:
sql3='drop table wuzzuf'

In [19]:
import pyodbc
conn=pyodbc.connect(
    "driver={ODBC Driver 17 for SQL Server};"
    "Server="+ Server +";"
    "Database=" + Database +";"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)
cursor=conn.cursor()

In [7]:
cursor.execute(SQL_Query1)

In [23]:
cursor.execute(sql3)

In [20]:
cursor.executemany(SQL_Query2,output)

In [21]:
cursor.commit()
conn.close()